import AosModule from "./module/AosModule.js";
import SwiperModule from "./module/SwiperModule.js";
import Select2Module from "./module/Select2Module.js";
import SideModule from "./module/SideModule.js";
import TabModule from "./module/TabModule.js";
import CollapseModule from "./module/CollapseModule.js?v=1.0";
import HeaderModule from "./module/HeaderModule.js";
import MobileModule from "./module/MobileModule.js";
import PopupModule from "./module/PopupModule.js";
import SmoothScrollModule from "./module/SmoothScrollModule.js";
import CountUpModule from "./module/CountUpModule.js";
import FancyboxModule from "./module/FancyboxModule.js";
import SearchModule from "./module/SearchModule.js";
import BtnToTopModule from "./module/BtnToTopModule.js";
import AnimatedModule from "./module/AnimatedModule.js";
import LoadMoreModule from "./module/LoadMoreModule.js";
import ComponentModule from "./module/ComponentModule.js?v=1.2";
import CheckModule from "./module/CheckModule.js";
import TextAniModule from "./module/TextAniModule.js";
import DatePickerModule from "./module/DatePickerModule.js";
import ParticlesModule from "./module/ParticlesModule.js";
import ScrollTriggerModule from "./module/ScrollTriggerModule.js";
import FaqModule from "./module/FaqModule.js";
import InfiniteslideModule from "./module/InfiniteslideModule.js";
import SetupFileInputs from "./module/SetupFileInputs.js";
import RangeModule from "./module/RangeModule.js";
import QuhuScrollModule from "./module/QuhuScrollModule.js";

const VERSION = Date.now();

window.addEventListener("DOMContentLoaded", async () => {
    AosModule();
    TabModule();
    AnimatedModule();
    SwiperModule();
    Select2Module();
    CollapseModule();
    HeaderModule();
    MobileModule();
    SmoothScrollModule();
    SideModule();
    PopupModule();
    CountUpModule();
    FancyboxModule();
    SearchModule();
    BtnToTopModule();
    LoadMoreModule();
    ComponentModule();
    CheckModule();
    TextAniModule();
    DatePickerModule();
    ParticlesModule();
    ScrollTriggerModule();
    FaqModule();
    InfiniteslideModule();
    SetupFileInputs();
    RangeModule();
    QuhuScrollModule();
});
